[package]
name = "powsql"
version = "0.0.1"
authors = ["Misko Lee imiskolee@gmail.com"]

[dependencies]
log = "0.3.6"
byteorder="*"
mioco = "*"
lazy_static="*"
openssl="*"
[[test]]
name = "test"
path = "test/mod.rs"
